package cai.tm.hotel.hotel.room.service.model;

import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseRoomEngaged;

/**
 * Generated by Jboot.
 */
@Table(tableName = "room_engaged", primaryKey = "id")
public class RoomEngaged extends BaseRoomEngaged<RoomEngaged> {
    public static final String ID = "id"; 
    public static final String ROOM_ID = "room_id"; 
    public static final String USER_ID = "user_id"; 
    public static final String ENGAGED_TIME = "engaged_time"; 
    public static final String CHECK_IN_TIME = "check_in_time"; 
    public static final String CHECK_OUT_TIME = "check_out_time"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time";


    @Override
    public String checkForAdd() {
        this.keep(ID, ROOM_ID, USER_ID, ENGAGED_TIME, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, ROOM_ID, USER_ID, ENGAGED_TIME, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
