package cn.tm.hotel.web.article.model;

import cn.tm.hotel.common.base.model.BaseArticle;
import io.jboot.db.annotation.Table;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName = "web_article", primaryKey = "id")
public class Article extends BaseArticle<Article> {
    public static final String ID = "id";
    public static final String AID = "id";
    public static final String MID = "mid";
    public static final String UID = "uid";
    public static final String VIEWS = "views";
    public static final String TITLE = "title";
    public static final String AUTHOR = "author";
    public static final String DESCRIBES = "describes";
    public static final String IMG = "img";
    public static final String CONTENT = "content";
    public static final String ADD_TIME = "addTime";
    public static final String PUB_TIME = "pubTime";
    public static final String LAST_EDIT_TIME = "lastEditTime";
    public static final String STATUS = "status";
    public enum Status{
        FORBIDDEN(-1), WAITING_FOR_CHECK(0), NORMAL(1), DELETE(2);

        private int status;

        Status(int status) {
            this.status = status;
        }

        public int getStatus() {
            return status;
        }
    }
}
