package cai.tm.hotel.user.feedback.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseUserFeedback;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_feedback", primaryKey = "id")
public class UserFeedback extends BaseUserFeedback<UserFeedback> {
    public static final String ID = "id"; 
    public static final String TITLE = "title"; 
    public static final String TYPE = "type"; 
    public static final String CONTENT = "content"; 
    public static final String USER_ID = "user_id"; 
    public static final String RECIVED_TIME = "recived_time"; 
    public static final String REPLIED_TIME = "replied_time"; 
    public static final String REPLY_CONTENT = "reply_content"; 
    public static final String STATUS = "status"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, TITLE, TYPE, CONTENT, USER_ID, RECIVED_TIME, REPLIED_TIME, REPLY_CONTENT, STATUS);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, TITLE, TYPE, CONTENT, USER_ID, RECIVED_TIME, REPLIED_TIME, REPLY_CONTENT, STATUS);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
