package cai.tm.hotel.user.account.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseUserAccount;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_account", primaryKey = "id")
public class UserAccount extends BaseUserAccount<UserAccount> {
    public static final String ID = "id"; 
    public static final String USER_ID = "user_id"; 
    public static final String DOLLAR = "dollar"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, USER_ID, DOLLAR, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, USER_ID, DOLLAR, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
