package cai.tm.hotel.hotel.coupon.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseHotelCoupon;

/**
 * Generated by Jboot.
 */
@Table(tableName = "hotel_coupon", primaryKey = "id")
public class HotelCoupon extends BaseHotelCoupon<HotelCoupon> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String TYPE = "type"; 
    public static final String COUNT = "count"; 
    public static final String DESCRIBE = "describe"; 
    public static final String START_TIME = "start_time"; 
    public static final String END_TIME = "end_time"; 
    public static final String CONDITION = "condition"; 
    public static final String CONDITION_LIMIT = "condition_limit"; 
    public static final String CONDITION_TARGET = "condition_target"; 
    public static final String CONDITION_DEPRECIATE = "condition_depreciate"; 
    public static final String STATEMENT = "statement"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, TYPE, COUNT, DESCRIBE, START_TIME, END_TIME, CONDITION, CONDITION_LIMIT, CONDITION_TARGET, CONDITION_DEPRECIATE, STATEMENT, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, TYPE, COUNT, DESCRIBE, START_TIME, END_TIME, CONDITION, CONDITION_LIMIT, CONDITION_TARGET, CONDITION_DEPRECIATE, STATEMENT, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
