package cn.tm.hotel.system.message.type.model;

import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseMessageType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "message_type", primaryKey = "id")
public class MessageType extends BaseMessageType<MessageType> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String DESCRIPTION = "description"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
