package cn.tm.hotel.system.permission.model;

import cn.tm.hotel.common.base.model.BaseRolePermission;

/**
 * Generated by Jboot.
 */
public class RolePermission extends BaseRolePermission<RolePermission> {
    public static final String ID = "id"; 
    public static final String ROLE_ID = "role_id";
    public static final String PERMISSION_ID = "permission_id";

    @Override
    public String checkForAdd() {
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
