package cn.tm.hotel.system.permission.model;

import cn.tm.hotel.common.base.model.BaseSystemPermission;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_permission", primaryKey = "id")
public class SystemPermission extends BaseSystemPermission<SystemPermission> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String TYPE = "type"; 
    public static final String DESCRIPTION = "description"; 
    public static final String SERVICE_ID = "service_id"; 
    public static final String CREATOR = "creator"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, TYPE, DESCRIPTION, SERVICE_ID, CREATOR, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, TYPE, DESCRIPTION, SERVICE_ID, CREATOR, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
