package cn.tm.hotel.system.permission.model;

import cn.tm.hotel.common.base.model.BaseUserPermission;

/**
 * Generated by Jboot.
 */
public class UserPermission extends BaseUserPermission<UserPermission> {

    @Override
    public String checkForAdd() {
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
