package cn.tm.hotel.web.modular.model;

import cn.tm.hotel.common.base.model.BaseModular;
import io.jboot.db.annotation.Table;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName = "web_modular", primaryKey = "id")
public class Modular extends BaseModular<Modular> {
	
}
