package cai.tm.hotel.user.account.flow.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseUserAccountFlow;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_account_flow", primaryKey = "id")
public class UserAccountFlow extends BaseUserAccountFlow<UserAccountFlow> {
    public static final String ID = "id"; 
    public static final String ACCOUNT_ID = "account_id"; 
    public static final String ORDER_ID = "order_id"; 
    public static final String TYPE = "type"; 
    public static final String AMOUNT = "amount"; 
    public static final String OPERATE_TIME = "operate_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, ACCOUNT_ID, ORDER_ID, TYPE, AMOUNT, OPERATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, ACCOUNT_ID, ORDER_ID, TYPE, AMOUNT, OPERATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
