package cn.tm.hotel.system.dict.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseSystemDict;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_dict", primaryKey = "id")
public class SystemDict extends BaseSystemDict<SystemDict> {
    public static final String ID = "id"; 
    public static final String KEY = "key"; 
    public static final String VALUE = "value"; 
    public static final String DESCRIPTION = "description"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, KEY, VALUE, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, KEY, VALUE, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
