package cai.tm.hotel.hotel.base.model;

import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseHotel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "hotel", primaryKey = "id")
public class Hotel extends BaseHotel<Hotel> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String TYPE = "type"; 
    public static final String ADDRESS = "address"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, TYPE, ADDRESS, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, TYPE, ADDRESS, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
