package cn.tm.hotel.user.base.model;

import cn.tm.hotel.common.base.model.BaseUser;
import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import org.tm.common.util.PatternUtils;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {
    public static final String ID = "id"; 
    public static final String USERNAME = "username"; 
    public static final String PASSWORD = "password"; 
    public static final String FACE_ID = "face_id"; 
    public static final String FIGERPRINT_ID = "figerprint_id"; 
    public static final String ID_CARD = "id_card"; 
    public static final String TEL = "tel"; 
    public static final String EMAIL = "email"; 
    public static final String NICK = "nick"; 
    public static final String REAL_NAME = "real_name"; 
    public static final String ADDRESS = "address"; 
    public static final String IMG = "img"; 
    public static final String BIRTHDAY = "birthday"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(USERNAME, PASSWORD, ID_CARD, TEL, REAL_NAME);

        // 手机号校验
        if(StrKit.isBlank(getTel())){
            return "手机号不能为空！";
        }else if(!PatternUtils.IsTelephone(getTel())){
            return "请输入合法的手机号";
        }

        // 身份证校验
        if(StrKit.isBlank(getIdCard())){
            return "身份证号不能为空！";
        }else if(!PatternUtils.IsIDcard(getIdCard())){
            return "身份证格式不正确";
        }

        // 真实姓名
        if(StrKit.isBlank(getRealName())){
            return "姓名不能为空！";
        }

        // 密码校验
        if(StrKit.isBlank(getPassword())){
            return "密码不能为空！";
        }else if(!checkPassword(getPassword())){
            return "密码长度必须由a-Z和0-9组成且长度为6-18位！";
        }

        // 用户名规则和密码规则一样
        if(StrKit.isBlank(getUsername())){
            return "用户名不能为空！";
        }else if(!checkUsername(getUsername())){
            return "用户名必须由中文、a-Z和0-9组成且长度为6-18位！";
        }

        setCreateTime();
        setUpdateTime();
        return "";
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, PASSWORD, TEL, EMAIL, NICK, REAL_NAME, ADDRESS, IMG, BIRTHDAY);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        if(StrKit.isBlank(getUsername())){
            return "用户名不能为空！";
        }else if(StrKit.isBlank(getPassword())){
            return "密码不能为空！";
        }

        return "";
    }

    public boolean checkUsername(String name){
        if(null == name) return false;
        String regex = "^[a-zA-Z0-9\u4e00-\u9fa5]{6,18}$";
        return name.matches(regex);
    }

    public boolean checkPassword(String password){
        if(null == password) return false;
        String regex = "^[a-zA-Z0-9_+/~!@#$%^&*(){}\\[\\]\"<>,.?':;|-]{6,18}$";
        return password.matches(regex);
    }

}
