package cai.tm.hotel.hotel.room.type.model;

import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseRoomType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "room_type", primaryKey = "id")
public class RoomType extends BaseRoomType<RoomType> {
    public static final String ID = "id";
    public static final String HOTEL_ID = "hotel_id";
    public static final String NAME = "name";
    public static final String DESCRIPTION = "description"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, DESCRIPTION, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
