package cai.tm.hotel.hotel.goods.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseHotelGoods;

/**
 * Generated by Jboot.
 */
@Table(tableName = "hotel_goods", primaryKey = "id")
public class HotelGoods extends BaseHotelGoods<HotelGoods> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String STOCK = "stock"; 
    public static final String PRICE = "price"; 
    public static final String ACTUAL_PRICE = "actual_price"; 
    public static final String DESCRIBE = "describe"; 
    public static final String HOTEL_ID = "hotel_id"; 
    public static final String VENDER_ID = "vender_id"; 
    public static final String PROVIDER_ID = "provider_id"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, STOCK, PRICE, ACTUAL_PRICE, DESCRIBE, HOTEL_ID, VENDER_ID, PROVIDER_ID, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, STOCK, PRICE, ACTUAL_PRICE, DESCRIBE, HOTEL_ID, VENDER_ID, PROVIDER_ID, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
