package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoomEngaged<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setHotelId(java.lang.String hotelId) {
		set("hotel_id", hotelId);
		return (M)this;
	}

	public java.lang.String getHotelId() {
		return getStr("hotel_id");
	}

	public M setRoomId(java.lang.String roomId) {
		set("room_id", roomId);
		return (M)this;
	}

	public java.lang.String getRoomId() {
		return getStr("room_id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setEngagedTime(java.util.Date engagedTime) {
		set("engaged_time", engagedTime);
		return (M)this;
	}

	public java.util.Date getEngagedTime() {
		return get("engaged_time");
	}

	public M setCheckInTime(java.util.Date checkInTime) {
		set("check_in_time", checkInTime);
		return (M)this;
	}

	public java.util.Date getCheckInTime() {
		return get("check_in_time");
	}

	public M setCheckOutTime(java.util.Date checkOutTime) {
		set("check_out_time", checkOutTime);
		return (M)this;
	}

	public java.util.Date getCheckOutTime() {
		return get("check_out_time");
	}

	public M setEngagedInTime(java.util.Date engagedInTime) {
		set("engaged_in_time", engagedInTime);
		return (M)this;
	}

	public java.util.Date getEngagedInTime() {
		return get("engaged_in_time");
	}

	public M setEngagedOutTime(java.util.Date engagedOutTime) {
		set("engaged_out_time", engagedOutTime);
		return (M)this;
	}

	public java.util.Date getEngagedOutTime() {
		return get("engaged_out_time");
	}

	public M setSalesPrice(java.lang.Float salesPrice) {
		set("sales_price", salesPrice);
		return (M)this;
	}

	public java.lang.Float getSalesPrice() {
		return getFloat("sales_price");
	}

	public M setTotalServicePrice(java.lang.Float totalServicePrice) {
		set("total_service_price", totalServicePrice);
		return (M)this;
	}

	public java.lang.Float getTotalServicePrice() {
		return getFloat("total_service_price");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}


	public M bookRoom() {
		return setStatus(0);
	}

	public M unBookRoom() {
		return setStatus(1);
	}

	public M checkInRoom() {
		return setStatus(2);
	}

	public M checkOutRoom() {
		return setStatus(3);
	}

}
