package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWebModular<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setWebMode(java.lang.String webMode) {
		set("webMode", webMode);
		return (M)this;
	}

	public java.lang.String getWebMode() {
		return getStr("webMode");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
