package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserCoupon<M extends BaseModel<M>> extends BaseModel<M>{

    public M setId(String id) {
        set("id", id);
        return (M)this;
    }

    public String getId() {
        return getStr("id");
    }

    public M setUserId(String userId) {
        set("user_id", userId);
        return (M)this;
    }

    public String getUserId() {
        return getStr("user_id");
    }

    public M setCouponId(String couponId) {
        set("coupon_id", couponId);
        return (M)this;
    }

    public String getCouponId() {
        return getStr("coupon_id");
    }

}
