package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRolePermission<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setPermissionId(String permissionId) {
		set("permission_id", permissionId);
		return (M)this;
	}

	public String getPermissionId() {
		return getStr("permission_id");
	}

	public M setRoleId(String roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public String getRoleId() {
		return getStr("role_id");
	}

}
