package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserOrder<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAmount(java.lang.Float amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Float getAmount() {
		return getFloat("amount");
	}

	public M setActualPayment(java.lang.Float actualPayment) {
		set("actual_payment", actualPayment);
		return (M)this;
	}

	public java.lang.Float getActualPayment() {
		return getFloat("actual_payment");
	}

	public M setCouponId(java.lang.String couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}

	public java.lang.String getCouponId() {
		return getStr("coupon_id");
	}

	public M setChargeExplain(java.lang.String chargeExplain) {
		set("charge_explain", chargeExplain);
		return (M)this;
	}

	public java.lang.String getChargeExplain() {
		return getStr("charge_explain");
	}

	public M setDeadline(java.util.Date deadline) {
		set("deadline", deadline);
		return (M)this;
	}

	public java.util.Date getDeadline() {
		return get("deadline");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
