package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWebArticle<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMid(java.lang.Integer mid) {
		set("mid", mid);
		return (M)this;
	}

	public java.lang.Integer getMid() {
		return getInt("mid");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setViews(java.lang.Integer views) {
		set("views", views);
		return (M)this;
	}

	public java.lang.Integer getViews() {
		return getInt("views");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}

	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return getStr("img");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

	public M setPubTime(java.util.Date pubTime) {
		set("pubTime", pubTime);
		return (M)this;
	}

	public java.util.Date getPubTime() {
		return get("pubTime");
	}

	public M setLastEditTime(java.util.Date lastEditTime) {
		set("lastEditTime", lastEditTime);
		return (M)this;
	}

	public java.util.Date getLastEditTime() {
		return get("lastEditTime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
