package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserFeedback<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setRecivedTime(java.util.Date recivedTime) {
		set("recived_time", recivedTime);
		return (M)this;
	}

	public java.util.Date getRecivedTime() {
		return get("recived_time");
	}

	public M setRepliedTime(java.util.Date repliedTime) {
		set("replied_time", repliedTime);
		return (M)this;
	}

	public java.util.Date getRepliedTime() {
		return get("replied_time");
	}

	public M setReplyContent(java.lang.String replyContent) {
		set("reply_content", replyContent);
		return (M)this;
	}

	public java.lang.String getReplyContent() {
		return getStr("reply_content");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
