package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserAccountFlow<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
		return (M)this;
	}

	public java.lang.String getAccountId() {
		return getStr("account_id");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setAmount(java.lang.Float amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Float getAmount() {
		return getFloat("amount");
	}

	public M setOperateTime(java.util.Date operateTime) {
		set("operate_time", operateTime);
		return (M)this;
	}

	public java.util.Date getOperateTime() {
		return get("operate_time");
	}

}
