package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserCard<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setIcCard(java.lang.String icCard) {
		set("ic_card", icCard);
		return (M)this;
	}

	public java.lang.String getIcCard() {
		return getStr("ic_card");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}

	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setVitualCard(java.lang.String vitualCard) {
		set("vitual_card", vitualCard);
		return (M)this;
	}

	public java.lang.String getVitualCard() {
		return getStr("vitual_card");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
