package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotelGoods<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public M setActualPrice(java.lang.Float actualPrice) {
		set("actual_price", actualPrice);
		return (M)this;
	}

	public java.lang.Float getActualPrice() {
		return getFloat("actual_price");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}

	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public M setHotelId(java.lang.String hotelId) {
		set("hotel_id", hotelId);
		return (M)this;
	}

	public java.lang.String getHotelId() {
		return getStr("hotel_id");
	}

	public M setVenderId(java.lang.String venderId) {
		set("vender_id", venderId);
		return (M)this;
	}

	public java.lang.String getVenderId() {
		return getStr("vender_id");
	}

	public M setProviderId(java.lang.String providerId) {
		set("provider_id", providerId);
		return (M)this;
	}

	public java.lang.String getProviderId() {
		return getStr("provider_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
