package cn.tm.hotel.common.base.model;

import org.tm.common.base.model.BaseModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotelCoupon<M extends BaseModel<M>> extends BaseModel<M>{

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.Integer getCount() {
		return getInt("count");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}

	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setCondition(java.lang.Integer condition) {
		set("condition", condition);
		return (M)this;
	}

	public java.lang.Integer getCondition() {
		return getInt("condition");
	}

	public M setConditionLimit(java.lang.Float conditionLimit) {
		set("condition_limit", conditionLimit);
		return (M)this;
	}

	public java.lang.Float getConditionLimit() {
		return getFloat("condition_limit");
	}

	public M setConditionTarget(java.lang.String conditionTarget) {
		set("condition_target", conditionTarget);
		return (M)this;
	}

	public java.lang.String getConditionTarget() {
		return getStr("condition_target");
	}

	public M setConditionDepreciate(java.lang.Float conditionDepreciate) {
		set("condition_depreciate", conditionDepreciate);
		return (M)this;
	}

	public java.lang.Float getConditionDepreciate() {
		return getFloat("condition_depreciate");
	}

	public M setStatement(java.lang.String statement) {
		set("statement", statement);
		return (M)this;
	}

	public java.lang.String getStatement() {
		return getStr("statement");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
