package cai.tm.hotel.user.card.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseUserCard;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_card", primaryKey = "id")
public class UserCard extends BaseUserCard<UserCard> {
    public static final String ID = "id"; 
    public static final String IC_CARD = "ic_card"; 
    public static final String ID_CARD = "id_card"; 
    public static final String VITUAL_CARD = "vitual_card"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, IC_CARD, ID_CARD, VITUAL_CARD, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, IC_CARD, ID_CARD, VITUAL_CARD, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
