package cn.tm.hotel.test.model;

import cn.tm.hotel.common.base.model.BaseTest;
import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "test", primaryKey = "id")
public class TestModel extends BaseTest<TestModel> {
    public static final String ID = "id"; 
    public static final String NICK = "nick"; 
    public static final String AGE = "age"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time";

    @Override
    public String checkForAdd() {
        this.keep(NICK, AGE);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NICK, AGE);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        if(StrKit.isBlank(getNick())){
            return "nick不能为空！";
        }
        return "";
    }
}
