package cai.tm.hotel.hotel.base.service.model;

import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseHotelService;

/**
 * Generated by Jboot.
 */
@Table(tableName = "hotel_service", primaryKey = "id")
public class HotelService extends BaseHotelService<HotelService> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String DESCRIPTION = "description"; 
    public static final String HOTEL_ID = "hotel_id"; 
    public static final String PRICE = "price"; 
    public static final String ACTUAL_PRICE = "actual_price"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, DESCRIPTION, HOTEL_ID, PRICE, ACTUAL_PRICE, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, DESCRIPTION, HOTEL_ID, PRICE, ACTUAL_PRICE, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
