package cn.tm.hotel.system.role.model;

import cn.tm.hotel.common.base.model.BaseSystemRole;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_role", primaryKey = "id")
public class SystemRole extends BaseSystemRole<SystemRole> {
    public static final String ID = "id"; 
    public static final String NAME = "name"; 
    public static final String DESCRIPTION = "description"; 
    public static final String CREATOR_ID = "creator_id"; 
    public static final String STATUS = "status"; 
    public static final String CREATE_TIME = "create_time"; 
    public static final String UPDATE_TIME = "update_time"; 

    @Override
    public String checkForAdd() {
        this.keep(ID, NAME, DESCRIPTION, CREATOR_ID, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID, NAME, DESCRIPTION, CREATOR_ID, STATUS, CREATE_TIME, UPDATE_TIME);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
