package cai.tm.hotel.user.operator.model;

import com.jfinal.kit.StrKit;
import io.jboot.db.annotation.Table;
import cn.tm.hotel.common.base.model.BaseUserOperator;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_operator", primaryKey = "id")
public class UserOperator extends BaseUserOperator<UserOperator> {
    public static final String ID = "id"; 

    @Override
    public String checkForAdd() {
        this.keep(ID);
        return super.checkForAdd();
    }

    @Override
    public String checkForUpdate() {
        this.keep(ID);
        return super.checkForUpdate();
    }

    @Override
    public String checkFiled() {
        /*if(StrKit.isBlank(getKey())){
            return "XX不能为空！";
        }*/
        return "";
    }
}
